### ISSUE TITLE
Spells

### ISSUE THREAD

**Issue by xXTheBoy** [TheComputerGeek2/MagicSpells#11]
I'm not sure why, however some certain spell-types and particles have stopped working. For example, combinations of particle projectiles which may include colored fireworks, or multi spells with coal block block breaking. Glass particles don't appear at all, and spells using these particles do not work, even trigger spells for instant mana spells, and instant mana spells in general do not work.. For example:

thecharge:
    spell-class: ".PassiveSpell"
    triggers: 
        - ticks 3
    chance: 100
    cooldown: 0
    modifiers:
        - sneaking required
    spells:
        - thecharge1
    always-granted: true

**Comment by TheComputerGeek2** [comment]
Thanks for the heads up, I've been doing some refactoring recently, so I'm not too surprised that something came up. Was this purely a graphical issue or did anything come up in the error logs? Also, may I see the full spell in question, including any dependencies for said spell? It would make it easier for me to understand what is going on if I haven't already found the issue through code digging.

**Comment by xXTheBoy** [comment]
I'm not sure whether it shows up in the console log, but it isn't there visually. I think there may be some. I'll have a look if you need me to. Anyway, an example of a spell that doesn't work:

thecharge1:
    spell-class: ".instant.ManaSpell"
    mana: 5
    effects:
        - caster particles blockcrack_95_11 0.6 0.6 0.2 100 0.7 75
        - caster particles blockcrack_95_3 0.6 0.6 0.2 100 0.7 75
        - caster particles blockcrack_95_11 0.6 0.6 0.2 100 0.2 75
        - caster particles blockcrack_95_3 0.6 0.6 0.2 100 0.2 75
        - caster sound mob.enderdragon.wings 0.2 0.1
thecharge:
    spell-class: ".PassiveSpell"
    triggers: 
        - ticks 3
    chance: 100
    cooldown: 0
    modifiers:
        - sneaking required
    spells:
        - thecharge1
    always-granted: true
thechargedummy1:
    spell-class: ".targeted.DummySpell"
    target-self: true
    effects:
        - target particles blockcrack_95_11 0.9 0.9 0.2 100 0.7 100
        - target bluesparkle
thecharge2:
    spell-class: ".MultiSpell"
    check-individual-cooldowns: false
    always-granted: true
    spells:
        - thecharge
        - thechargedummy1
        - DELAY 3
        - thecharge
        - thechargedummy1
        - DELAY 3
        - thechargechakra
        - thechargedummy1

**Comment by TheComputerGeek2** [comment]
It turned out that the issue was in fact from the migration to effect lib, I had neglected in line material data when updating the back end handling to effect lib. The most recent commits should address that part. Also, for future reference, you can usually pull up a lot of config errors, when present, by running /c reload
This will reinitialize the plugin's spells and settings.

**Comment by xXTheBoy** [comment]
Aye thanks, if you don't mind me asking; could I have an updated download link for your MagicSpells.jar? I would appreciate it, thanks!

**Comment by TheComputerGeek2** [comment]
Try this one out, let me know if it works for you. https://github.com/TheComputerGeek2/MagicSpells/releases/tag/3.4.2-dev-1511191021
Also, you're more than welcome to just build from source as well, just remember to also keep an effect lib jar in your plugins folder. Most effects rely on it still.
If this works, I'll go ahead and close the issue.

**Comment by xXTheBoy** [comment]
It works, thanks! Also, I know this isn't something to do with this plugin; but on every 1.8 MagicSpells+ the glass blockbreaking, no matter what colour turns white. Do you have any idea why?

**Comment by xXTheBoy** [comment]
Bump?

**Comment by tara81** [comment]
hi xxtheboy : try this version 
Magicspells jar: http://www.mediafire.com/download/35ku9qjj6x2s0ny/MagicSpells.jar
Its the version with the least amount of bugs at this time.

Check out the forums too =)
http://nisovin.com/forums/index.php?threads/magicspells-fork-of-effectslib.1319/
