### ISSUE TITLE
With the iline version - Bugs I noticed

### ISSUE THREAD

**Issue by tara81** [TheComputerGeek2/MagicSpells#12]
1. Line effect doesn't work properly with reddust, flame particles. (the particle line goes into the air instead of towards the target). It does however work properly with hearts particle.
2. My huge particle projectile spell lags the server and does not cast. 
   (something majorly wrong with particle projectile spells)
   Spell config: http://pastebin.com/utpxgab0
   Timings: http://timings.aikar.co/?url=13474431
3. :\* to ignore item duration is no longer supported. 
   WARN]: [MagicSpells] java.lang.NumberFormatException: For input string: "*"

(example: spell config: http://pastebin.com/1YQsKfP1 )

**Comment by Chronoken** [comment]
Most of those issues have been resolved in the 4.0 beta builds.
