### ISSUE TITLE
Please Help ;-;

### ISSUE THREAD

**Issue by Unknownistic** [TheComputerGeek2/MagicSpells#125]
Im a newbie to MagicSpells and i Wanted to do the ParticleProjectile Things Can anyone help me with it? i tried it from someone on the latest release of MagicSpells on a 1.10.2 Server and it didnt work.. PLZ HELP!!

**Comment by DragonsAscent** [comment]
You will not receive support on GitHub.
Issues are not the way to get support and it shows you haven't read the readme.

Go there.
