### ISSUE TITLE
Blockcrack Particle

### ISSUE THREAD

**Issue by Thrashyy** [TheComputerGeek2/MagicSpells#13]
Hello, as you may know, their is a small blockcrack issue.
Here are some of the things that make it not work.
Madaracustomjutsulolderpaherp:
    spell-class: ".instant.ParticleProjectileSpell"
    tick-interval: 1
    tick-interval: 1
    special-effect-interval: 1
    particle-name: blockcrack_35_0
    particle-speed: 20
    particle-count: 300
    particle-horizontal-spread: 5.0
    particle-vertical-spread: 5.0

If the particle-name is blockcrack, the particle projectile doesn't even register as a spell basically. Also, you can't use blockcrack_ITEM_DATA anywhere. If it contains a data, it will show up as pink clay or something. I will pay to get it fixed right now, its a priority for me.

**Comment by TheComputerGeek2** [comment]
What version of MagicSpells, spigot, and effectlib are you using? Also, did you get any error in the console on /c reload
I recently had made some patches which made this effect functional.

**Comment by Thrashyy** [comment]
I downloaded the version of magicspells that you had, do I need two magicspells downloaded, yours and nisovins? I was using bukkit version 1.8 as well, I will try it with spigot now. Also yes, during the c reload it was just giving particle projectile errors, 

Error message : http://pastebin.com/SHcKdSWc
Spell that causes the error : http://pastebin.com/Pmhm97bB

So yes, the error seems to be that any particle projectile with the main particle (particle-name:) as blockcrack, will not load. It can be a special effect though, but even then it will be pink clay if it gets an ID. 
Example: blockcrack_7_1 
this will not work what so ever, no matter what. Due to it having an ID.

**Comment by Thrashyy** [comment]
Could I get the link to the newest update of your magicspells fix?

**Comment by TheComputerGeek2** [comment]
https://github.com/TheComputerGeek2/MagicSpells/releases try one of the latest two on there, although do read the warnings attached, as there are rather important.
And all you need is one magicspells jar and the effectlib jar to function, having more than one magicspells jar at once would likely cause problems. Let me know if this works out, just be aware that the bubble particle will not function and will throw errors, I am aware of this and it is on my priority list for addressing.

**Comment by Thrashyy** [comment]
Yeah I pretty experienced with making spells, but from what happened with me. It would not load the ParticleProjectile if the main particle (particle-name:) was equal to blockcrack_ANYBLOCK_ANYID

Also, no ID would register. If it got an ID, it would just fill in a random block, usually red/pink clay.

**Comment by TheComputerGeek2** [comment]
is this still a problem with the new one? if so, I'd like to see the usage context

**Comment by Thrashyy** [comment]
Considering the last release was a day ago, and I tested it this morning, I assume that it still is broken for the new one.

I will give a free examples using pastebin, I hope that is fine.

http://pastebin.com/y7TNfPdz

The reason is doesn't work, is because the "Particle-name" right under the spell interval, is a blockcrack. Each and every spell in my config that contained that blockcrack in the particle projectiles main particle got disabled, and wasn't accessible in game.

If it makes it easier for you, you can add my skype. Just incase;
Skype: Thrashysenpai

**Comment by TheComputerGeek2** [comment]
So a few things from asking around: one of them is that with the latest, people have been able to specify the block data, although also got a suggestion of removing the data part for now. As far as I'm aware, the metadata is still bugged, but haven't had any issue with the block type or item type on the latest version otherwise.

And last point is the Minecraft version: is this reproducible on 1.8? I noticed that you were running 1.7. Furthermore, I ask that you not assume it is still broken unless you are positive through testing.

**Comment by Thrashyy** [comment]
I stated that I used it on spigot and bukkit 1.8, tried it with both.

**Comment by Thrashyy** [comment]
After the newest update 7 days ago, the blockcrack in all the paritcle projectiles is working, but their is small bugs that do not make much sense. Such as the max-range and max-duration on particle projectiles not working, on some of the spells tend to fall as soon as its casted, as if it had a huge gravity. Although, the gravity on all of them are 0.
