### ISSUE TITLE
spell WATER and LAVA   spell-class: ".targeted.MaterializeSpell"

### ISSUE THREAD

**Issue by Yukyxy** [TheComputerGeek2/MagicSpells#150]
Hello i have this error magic spell v3.5-dev-1806271923
impossible cast spelle water / lava in 1.12.2 now

[10:15:55] [Server thread/ERROR]: [MagicSpells] This error has been saved in the errors folder
[10:15:55] [Server thread/ERROR]: [MagicSpells] AN EXCEPTION HAS OCCURED:
[10:15:55] [Server thread/ERROR]: [MagicSpells]     null (java.lang.reflect.InvocationTargetException)
[10:15:55] [Server thread/ERROR]: [MagicSpells]     null (java.lang.NullPointerException)
[10:15:55] [Server thread/ERROR]: [MagicSpells] This error has been saved in the errors folder

**Comment by AllTheCode** [comment]
>  [MagicSpells] This error has been saved in the errors folder
In order to debug and test this further, we will need the log from the errors folder, as it describes the error in a level of detail that is needed to fix this. In addition, could you post your spell configuration?

**Comment by Yukyxy** [comment]
error log https://pastebin.com/ZJcXQcYh

i use this regular_water:
    spell-class: ".targeted.MaterializeSpell"
    name: water
    spell-icon: water_bucket
    description: Summons a water spring into existence.
    cast-item: stick
    cooldown: 120
    range: 8
    block-type: water
    reset-delay: 200
    apply-physics: true
    check-plugins: true
    cost:
        - mana 10
    str-cost: 10 mana
    str-no-target: No tar

----------------------------------------------
Finally, I was forced to use stationary water with the anvil spell to summon water that does not grief the claims of players... :( 
The water does not flow with this , but I can still summon the water in a claim "grief prevention"

Thank you for you help

**Comment by AllTheCode** [comment]
This seems to be an error with the new pattern feature of the MaterializeSpell, used to allow patterns to form more complex features. However, it retrospectively broke all old materialize spells. Keep this open, as some arguments such as use-pattern and block-type are assigned but not referenced later and don't do anything, but I've written an updated spell for you.
`water:
    spell-class: ".targeted.MaterializeSpell"
    name: water
    spell-icon: water_bucket
    description: Summons a water spring into existence.
    block-type: water
    cast-item: stick
    cooldown: 120
    range: 8
    reset-delay: 200
    apply-physics: true
    check-plugins: true
    cost:
        - mana 10
    str-cost: 10 mana
    str-no-target: No target found
    use-pattern: true
    patterns:
        - "water"`

**Comment by Yukyxy** [comment]
thank you for example it's work now ^^
