### ISSUE TITLE
Change fake spells to check for permission

### ISSUE THREAD

**Issue by TheRealDxRed** [TheComputerGeek2/MagicSpells#151]
While setting up a server, I found it would be really useful to have fake spells like `forcecast` and `reload` assigned to a permission node instead of just checking if the player is an OP. I think this would benefit anyone who runs a server with some kind of ranking/grouping system.

I'm not too familiar with the Bukkit/Spigot APIs, but I'm sure theres a quick way to switch `sender.isOP()` for something like: `sender.hasPermission("magicspells.whatever")`

**Comment by AllTheCode** [comment]
Pull request #153 should add this.

**Comment by TheRealDxRed** [comment]
Thanks for letting me know. Now I can finally edit/create spells without switching to my server console after every change!

Cheers
