### ISSUE TITLE
tree and lifewalk spell = grief?

### ISSUE THREAD

**Issue by Yukylyu** [TheComputerGeek2/MagicSpells#158]
Hello my players can to grief zones worldguard and grief prevention with these two spells how to protect the zones, please?

lifewalk:
    spell-class: ".buff.LifewalkSpell"
    name: LifeWalk
    spell-icon: sapling:2
    cast-item: book
    tick-interval: 15
    red-flower-chance: 15
    yellow-flower-chance: 15
    sapling-chance: 0
    cooldown: 5
    tallgrass-chance: 25
    fern-chance: 15
    cost:
        - mana 10
        - feather 1
    use-cost:
        - feather 1
--------------------------------------
tree:
    spell-class: ".targeted.TreeSpell"
    name: Tree
    spell-icon: sapling
    cast-item: stick
    range: 15
    prevent-landing-blocks: true
    cooldown: 15
    tree-type: tree
    animation-speed: 20
    check-plugins: true
    cost:
        - mana 30
        - wheat 10
    use-cost:
        - wheat 10

**Comment by Big-Meli** [comment]
Make a no-cast-zone that only disallows that spell

**Comment by Yukyxy** [comment]
And for Grief prevention?

**Comment by NoblessHamster** [comment]
Add Grief-Prevention plugin
you can resolve that

**Comment by Chronoken** [comment]
No updates here so i'll close it.
