### ISSUE TITLE
Attributes assumming all slots causing them to appear multiple times

### ISSUE THREAD

**Issue by mikassio** [TheComputerGeek2/MagicSpells#29]
>     
Hello.
Help me please.
http://rgho.st/8QSdfhlgM/thumb.png

Code:
>      BasicChestplate:
          type: "diamond_chestplate"
          name: "&6Diamond Chestplate"
          lore:
            - "&5Don't let the gold name fool you,"
            - "&5it's definitely made of diamond."
          attributes:
              attr1: "generic.maxHealth 5"

**Comment by omega015** [comment]
What do you need help with?

**Comment by mikassio** [comment]
I understand it is a bug, which TheComputerGeek2 did not know?

**Comment by TheComputerGeek2** [comment]
@mikassio I'm already aware of this issue, the reason for it is due to legacy support prior to the times when modifiers would be specific to a certain slot. Although perhaps it is time to revisit this since 1.7 support was dropped.

**Comment by mikassio** [comment]
When you fix?

**Comment by TheComputerGeek2** [comment]
Addressed by 3385aaf4075b9ac78afa7f9f40d5b78e86b2b586
please note the changes required in order to specify a slot.
