### ISSUE TITLE
Passive spell being cast multiple times

### ISSUE THREAD

**Issue by omega015** [TheComputerGeek2/MagicSpells#30]
While testing a passive spell with a trigger I notice that the spell is being cast twice. I tested using the latest release. 

This is the spell: http://pastebin.com/UgQNwedv

Do you need anything else? Hopefully its not just me, but I can rebuild a test server using no other plugins if any of those might be interfering.

**Comment by omega015** [comment]
Does untagged-6881b01a85e24eecfc8c have anything to do with this issue or is that something else?

Thanks.

**Comment by TheComputerGeek2** [comment]
@omega015 it is exactly this, along with a few other variants of the issue. Including the double scrolling, and variants of the right click based triggers.
