### ISSUE TITLE
multiline lore on items

### ISSUE THREAD

**Issue by Bodyash** [TheComputerGeek2/MagicSpells#31]
Not working :c
https://pp.vk.me/c638019/v638019866/151af/XEqUJ02bvjU.jpg
https://pp.vk.me/c638019/v638019866/151a6/JS9_oQMPEvI.jpg

For examle:
```
str-scroll-subtext: 
- "&e Наносит 7 ед. урона горящим врагам и" 
- "&e восстанавливает 1 ед. здоровья за каждую цель."
```

Looks like:
https://pp.vk.me/c638019/v638019866/15190/EuyTgO2K_RI.jpg

**Comment by TheComputerGeek2** [comment]
@Bodyash A few things.

First, things for bringing up this issue, I haven't heard of this one before.

Second, I'm surprised that example would work at all, as the type it asks for seems to be a string, not a list of strings.

That said, this should be a fairly easy fix. I hope to have this fixed within a day or so. I have a few other bug fixes in progress so I need to address them first.

**Comment by Bodyash** [comment]
str-multi-line: "You can use a slash n\nto make a new line" - \n working for chat, but not for items C:

Ty much. And can use use Maven instead of Ant? It`s very hard to compile with Ant

**Comment by TheComputerGeek2** [comment]
I don't have any intention of moving over to maven. Ant has always been my preferred builder system and I haven't encountered any difficulties building with it, so I'm unsure as to what the problem you're having with it is. At most, I might end up using ivy to manage dependencies.
