### ISSUE TITLE
Nova Effect - Data option is not working

### ISSUE THREAD

**Issue by Chronoken** [TheComputerGeek2/MagicSpells#32]
position: special
height-offset: 1
effect: nova
type: 155
data: 1
radius: 0
expand-interval: 20

This effect should spawn a chiseled quartz, but spawns the normal quartz, tested on stained clay and stained glass, nothing works.
Im using the latest build, server version 1.10.2.

**Comment by TheComputerGeek2** [comment]
@Chronoken because there is no option that is ever read called data in that effect. You are trying to do something that simply does not exist in that form.
