### ISSUE TITLE
MagicSpells Memory issue

### ISSUE THREAD

**Issue by zDrakon** [TheComputerGeek2/MagicSpells#33]
https://hastebin.com/cucevuwefa.vbs

I used /memory and configured all my spells to have memory: 10 with the default having 50 so each player can only have 5 spells at a time.

Except... That happened. 

Spigot 1.8.8

What I basically am trying to do is give all players access to all spells (except dangerous ones) but they can only have 5 at a time.

**Comment by TheComputerGeek2** [comment]
please include the version of magicspells itself in addition to the version of the memory addon.

**Comment by zDrakon** [comment]
Latest versions on releases page.

**Comment by zDrakon** [comment]
Magicspells Memory v1.2-dev-1701060630

MagicSpells from your relases page.

**Comment by zDrakon** [comment]
any update on getting this fixed? I might have to release my survival world without spells ;(

**Comment by MidnightChipmunk** [comment]
If its very crucial for your server I recommend setting up a variable system for now until this gets patched.

**Comment by zDrakon** [comment]
Variable system? mind expanding on that :( ?

**Comment by MidnightChipmunk** [comment]
Something like whenever someone learns a spell add one to their already known spells and if they reach the max and want to learn a new one make them forget a spell and decrease their known spells by one when they forget it. Its kind of a knockoff brand of the memory addon.

**Comment by zDrakon** [comment]
if I offered $10 for a fix on this ASAP as #1 priority, can that happen @TheComputerGeek2 ?
