### ISSUE TITLE
Support 1.9+ Datavalues for potions and spawn eggs

### ISSUE THREAD

**Issue by LihP** [TheComputerGeek2/MagicSpells#34]
Some items like potions and spawn eggs cannot be used via predefined items or conjure spells since the 1.9 changes from datavalues to nbt tags. It would be great to see support for these items, thanks again for maintaining this awesome plugin! 

PS, since nisovins forums are down, where are people discussing magic spells?

**Comment by TheComputerGeek2** [comment]
@LihP the egg fix is actually in the next commit already.
And we use a group skype chat for discussing magicspells now. You can join using the following:
`join skype com/PZG3k04HLDn4` but replace the spaces with . (broke it so that bots won't follow)

**Comment by LihP** [comment]
Oh that's great news, and thank you for the skype link, I will get on there as often as I can.

**Comment by LihP** [comment]
Forgot to mention, when using the potioncolor option for predefined potions items, the modifier "hasitemmorethan" and possibly others don't recognise the item, works great after I remove the color.
