### ISSUE TITLE
Fix land spell in LeapSpell

### ISSUE THREAD

**Issue by Yahumoo** [TheComputerGeek2/MagicSpells#360]
There is land spell in LeapSpell but that is working on fall damage. I want to use land spell that is working on NOT fall damage

I'm Korean so that grammer may be not correct

**Comment by JasperLorelai** [comment]
Could you please provide your Minecraft version (`/version`), your MagicSpells version (`/version MagicSpells`), and the spell configuration used?

**Comment by Yahumoo** [comment]
My minecraft version is **(Implementing API version 1.16.3-R0.1-SNAPSHOT)** and MagicSpells version is **(4.0-Beta-7)**

**Comment by Chronoken** [comment]
Fixed with commit: fcc7e0c
