### ISSUE TITLE
I can't use holdingprecise in modifiers

### ISSUE THREAD

**Issue by Yahumoo** [TheComputerGeek2/MagicSpells#362]
I want to use holdingprecise but it doesn't work.
```
modifiers:
    - holdingprecise [magicitem] require
```
Is it right?

**magicspells version: 4.0 beta-6
minecraft version: 1.16.3**

**Comment by gloamingwildwoods** [comment]
It's 'required', not 'require'

**Comment by Yahumoo** [comment]
I already did it but didn't work

**Comment by Chronoken** [comment]
Please use the discord for spell issues.
