### ISSUE TITLE
Would like to share Magicspells to mcbbs.net?

### ISSUE THREAD

**Issue by xuanzhoujun** [TheComputerGeek2/MagicSpells#368]
Hello,I'm a Chinese Server Owner and MC Lover.3 years ago,I got to know Magicspells,3 years later, I finally found here.It's a greatful and epoch-making plugin.In the past ,someone from China introduced this plug-in to our Chinese users and I'm one of them.Now I I have just know that the forum had been moved and the plug-in had arrived here.So I wan't to Formally Introduce the community and the reborn plugin to the Chinese users.I admire the agile feature of Magicspells,andI believe most Chinese think so.Now I really want to repost Magicspells to mcbbs.net(The biggest MC forum in China)If you agree ,I'll be responsible for most of the data which can be translate to Chinese and invite Chinese users to come here.Support your work and we look forward to your approval.

**Comment by Chronoken** [comment]
Use discord for communication, issues is for bug reports.
