### ISSUE TITLE
MagicSpells Forum

### ISSUE THREAD

**Issue by Shinidk** [TheComputerGeek2/MagicSpells#37]
Hey,

Everytime i try to log into the forum to check your posts it keeps saying error! Do you know what is wrong and when it will be fixed ?

**Comment by TheComputerGeek2** [comment]
@Shinidk the forums are down as far as I know, and I am not aware of any plans for its revival. However, as mentioned here https://github.com/TheComputerGeek2/MagicSpells/issues/34#issuecomment-274993337 there is a skype group which people hang out in to discuss magicspells.
