### ISSUE TITLE
target-modifiers is not work

### ISSUE THREAD

**Issue by votica** [TheComputerGeek2/MagicSpells#38]
Precautions: I can't speak English very well.

target-modifiers is not work.
But AreaEffectSpells's entity-target-modifiers/location-target-modifiers work fine

fix plz. thank you

magicspells version: lasted,
cmd error: null

**Comment by Thaumcraft4Lyfe** [comment]
You don't need target-modifiers for AOEs. You use the other two, where one targets the entities and one targets the locations. Self-explanatory to me.
