### ISSUE TITLE
target-modifiers not work

### ISSUE THREAD

**Issue by votica** [TheComputerGeek2/MagicSpells#39]
The old question was an error in translation.
Let me give you an example.

TEST:
    spell-class: ".targeted.AreaEffectSpell"
    horizontal-radius: 16
    vertical-radius: 16
    max-targets: 0
    spells: 
        - TEST-Pain
TEST-Pain:
    spell-class: ".targeted.PainSpell"
    can-target: players, nonplayers
    damage: 1
    target-modifiers:
        - entitytype zombie required

Even if entity type is not zombie, it suffers damage.

**Comment by DragonsAscent** [comment]
Target modifiers work fine. AreaEffectSpells use "entity-target-modifiers".
