### ISSUE TITLE
GlowSpell

### ISSUE THREAD

**Issue by MarlePG** [TheComputerGeek2/MagicSpells#402]
MagicSpells Version magicspells version: 4.0 beta-8
minecraft version: 1.16.4

Spell: 
glow:
    spell-class: ".targeted.ext.GlowSpell"
    cast-item: paper
    toggle: true
    duration: 100
    client-side: false
    update-period: 20
    colors: blue

Error:
[WARNING] .... [MagicSpells] Unable to load spell glow (missing/malformed class com.nisovin.magicspells.spells.targeted.ext.GlowSpell)

**Comment by DragonsAscent** [comment]
You can't use a spell that doesn't exist in your version.

**Comment by MarlePG** [comment]
What version do I have to download to use it?

**Comment by Chronoken** [comment]
Issues tab is for reporting bugs that occur when using the plugin, if you need help with spells, please join our plugin discord: https://discord.gg/FJXfDPZ
