### ISSUE TITLE
You can't use a spell that doesn't exist in your version.

### ISSUE THREAD

**Issue by MarlePG** [TheComputerGeek2/MagicSpells#403]
You can't use a spell that doesn't exist in your version.

_Originally posted by @DragonsAscent in https://github.com/TheComputerGeek2/MagicSpells/issues/402#issuecomment-773804759_

What version do I have to download to use it?

**Comment by Chronoken** [comment]
Issues tab is for reporting bugs that occur when using the plugin, if you need help with spells, please join our plugin discord: https://discord.gg/FJXfDPZ
