### ISSUE TITLE
.targeted.CaptureSpell doesn't produce eggs for newer mobs

### ISSUE THREAD

**Issue by VoxPopuliZombiemold** [TheComputerGeek2/MagicSpells#41]
Llamas, Polar Bears, Stray, Shulker, etc do not produce eggs when using the ".targeted.CaptureSpell".

Saw this:

https://hub.spigotmc.org/jira/browse/SPIGOT-2813?jql=text%20~%20%22llama%22

Work around?

**Comment by TheComputerGeek2** [comment]
@VoxPopuliZombiemold thanks for the heads up, I'll work on getting that fixed over this weekend. Perhaps this would also be the time to give the capture spell a bit of TLC.

**Comment by VoxPopuliZombiemold** [comment]
@TheComputerGeek2 Shoot me an email zombiemold@gmail.com

I'd love to work out an arrangement wherein we could commission some specific changes/bug fixes. I'd be happy to pay up front to get things going :)

**Comment by VoxPopuliZombiemold** [comment]
I just wanted to re-float this offer. Our server is looking to invest development money into guided changes bug fixes and additions to MagicSpells if you or anyone around here is interested. Just send me an email :)

**Comment by Chronoken** [comment]
Fixed in 4.0
