### ISSUE TITLE
A timed conjure spell

### ISSUE THREAD

**Issue by HyperDioxide** [TheComputerGeek2/MagicSpells#42]
Hello! I would like to request a spell.
Is it possible to make a timed conjure spell?
A spell that conjures an item from the predefined items etc and then removes that item after a specific amount of time.
Example : I conjure a wooden hoe that casts a spell, after x amount of time that wooden hoe is removed from the inventory  like the armor buff spell which lets you have the armor for an amount of time before being removed.
This wooden hoe has lore, a name, attributes etc.
I would really appreciate this as it will help a magic kit for a planned server.
I understand if this is not possible or if you do not desire to make it.
Thanks!

**Comment by TheComputerGeek2** [comment]
Already exists: https://github.com/TheComputerGeek2/MagicSpells/blob/master/src/com/nisovin/magicspells/spells/instant/ConjureSpell.java#L86
