### ISSUE TITLE
SpellTargetEvent fired twice

### ISSUE THREAD

**Issue by Tomut0** [TheComputerGeek2/MagicSpells#449]
Is it okay that it's called twice? 👀 
If it is, then how I can make it firing only once? (And yes, I tried to use `ignoreCancelled = true`)
![Снимок](https://user-images.githubusercontent.com/42711312/114285487-3912bf80-9a60-11eb-83c1-9ccc2900d5ad.PNG)

**Comment by Chronoken** [comment]
We need more info than just a screenshot. Send your code or explain your issue on the official MS discord: https://discord.gg/6bYqnNy

**Comment by Tomut0** [comment]
Well, it was some month ago. 😅 
Thanks for the answer anyway.
