### ISSUE TITLE
Open a PR to the main repository

### ISSUE THREAD

**Issue by johnsudaar** [TheComputerGeek2/MagicSpells#45]
There is no point of maintaining multiple versions. Why not openning a PR on the nisovin repo. All these greate feature would be a great advancement for the other users.

Thanks for your awesome work !

**Comment by TheComputerGeek2** [comment]
@johnsudaar this is already readily available to the 'other users' http://nisovin.com/magicspells/#download

**Comment by johnsudaar** [comment]
My bad ! Thanks for your work !
