### ISSUE TITLE
.targeted.SummonSpell doesn't use target-modifiers

### ISSUE THREAD

**Issue by Zoagel** [TheComputerGeek2/MagicSpells#46]
First of all, because I don't have any other way to contact you, thank you so much for keeping this project alive, I love your work.

I was wondering if you could make the .targeted.SummonSpell (summon) support target-modifiers. This would allow admins to create long and shortrange summon spells for example.

Currently it is only possible to check the modifiers of the casting player, not the targeted player (by the summon).

**Comment by DragonsAscent** [comment]
This could be a useful feature. I'll back this tbh.
