### ISSUE TITLE
Cannot seem to find %t in this spell. Used to work. Is it borked?

### ISSUE THREAD

**Issue by Coldene** [TheComputerGeek2/MagicSpells#462]
Hi there! Gosh.. First I just want to say. I have used this plugin since 1.8 MC Nisovin days.
Many servers and MC versions later I still cannot make a server without this plugin.
I thought Nisovin was the best coder of plugins I had ever experienced. Still think he was godly 
plugin guy. You know yourself how powerful the plugin is. After 1.12 I was forced to 
go with your forked version and up to that point I was a bit skeptical of your fork so 
I had not used it. After getting to grips with the slight changes I have to say... 
Bloody well done, you!!! The plugin is even more powerful that it used to be.
I have 58 plugins on my current server. Many top plugins. 

Yours is still my top plugin. This my current server details if interested. 
https://www.planetminecraft.com/server/piper-survival-3842308/
It is only because you kept the plugin going that I keep going with MC. 
My servers are all 100% totally free, spent £1000s on hosted servers, every single one 
had MagicSpells. All for players who could never/would never buy ViP perk on other servers. 
100% EULA compliant. I greatly appreciate any time you give reading this. Hope it's not 
too nooby a bug report. It might not even be a bug. Written 1000s of spells, many complex 
ones... But this unexpected thing though!!!

So this issue then, spent hours going nuts trying to get it to work again yet it don't seem 
to find the target. It's a PvP spell supposed to cause meaty particles and explosion when player 
kills other player. The target player's named player_head flies off and floats away on fire allowing 
the killer to loot the head + some xp and some random PVP kill drops. The head flying 
thing always cought players by surprise + the particles. Not exactly a forgettable kill.
This is pastebin of the spell set that does it. What am I doing wrong? Can you see anything 
wrong with the spell or target placeholders or is it broke? https://pastebin.com/7Wq8A7yW

MagicSpells v4.0-Beta-8
Version. git-Paper-762 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Other plugins (58): AntiDisconnectSpam, AutoLapiz*, Autorank, CaneBully*, ChargedCreeper*, ChatInjector*, ChestShop, ClearLag, ColoredSigns*, CoralStay, CoreProtect, CrazyAuctions, dynmap*, Dynmap-PreciousStones*, DynmapEssentials, EditableSign, EffectLib*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, ExoticGarden, GroupManager, HoloDropsX, HolographicDisplays, HolographicExtension, Jobs, LandValue*, LibHatesMods, LibsDisguises, LiteXpansion, LWC, MagicSpells, mcMMO, MobCapturer, Multiverse-Core, Multiverse-Inventories, MyPet, MyPreciousStone*, PlaceholderAPI, PlayerVaults, PreciousStones, ProtocolLib, PvPToggle, RandomTeleport*, RecipeManager, SFCalc, SignLoggerPlus*, SilkSpawners, Slimefun, Towny, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, Zenchantments

I sincerely thank you for any time you give this post. And.. for your work on managing MagicSpells. 
Thank you!!! Very much!!!

**Comment by DragonsAscent** [comment]
If you need help with plugin issues, please come to our discord https://discord.magicspells.com/. The GitHub is for posting bugs.

**Comment by Coldene** [comment]
> If you need help with plugin issues, please come to our discord https://discord.magicspells.com/. The GitHub is for posting bugs.

I and many others do not use Discord as it has a rep for considerably obnoxious and pervy community.
It's also a bit bewildering to use as a new user. Not user friendly at all (IMO)
Also admins and moderators of servers there tend to be a bit rude or abusive. No thanks.

**Comment by Chronoken** [comment]
Cannot reproduce it on the latest Beta 10 dev build, used a simple broadcast command to display the caster and target names: https://pastebin.com/4D1vAPnp

To get access to Beta 10 dev builds, you have to join our discord and ask staff for the tester role.
