### ISSUE TITLE
FishListener.class not found  PassiveSpell 'HugePearls' has an invalid trigger defined: fish

### ISSUE THREAD

**Issue by Coldene** [TheComputerGeek2/MagicSpells#467]
Gone with the wind... ?
Had a bunch of fish event drops usaing command spells to drop 
player_heads with fish and gems.

Is it gone forever?

**Comment by DetectiveComics** [comment]
![image](https://user-images.githubusercontent.com/26725183/122681070-2e8b4980-d1b8-11eb-8721-d9396c2ef1fe.png)
