### ISSUE TITLE
NCP issues with projectiles

### ISSUE THREAD

**Issue by emmanuelvlad** [TheComputerGeek2/MagicSpells#47]
There's an issue with projectiles and NCP : `Tried to throw projectiles too quickly`

Spell used `.instant.FreezeSpell`

**Comment by TheComputerGeek2** [comment]
Thank you, I will look into this when I get a chance, could you also specify which versions this happens on? (Server version, server type, Magicspells version (including build number), NCP version, NCPC version)

This will make it easier for me to resolve the issue.

**Comment by RednedEpic** [comment]
I've had the same issue as well. 

PaperSpigot: git-Paper-1452 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT). 
Latest MagicSpells: (3.5-dev-1807290045). 
NoCheatPlus: 3.15.2-SNAPSHOT-sMD5NET-b1113.
CompatNoCheatPlus: v6.6.3-SNAPSHOT-sMD5NET-b87.

Thanks!
