### ISSUE TITLE
Issue with /menu

### ISSUE THREAD

**Issue by StarGlaxeon** [TheComputerGeek2/MagicSpells#478]
https://pastebin.com/vazYCTv7 I have an issue with magicspells whenever i do /menu it wont come up and gives me alot of problems

**Comment by JasperLorelai** [comment]
One of the options on your menu is missing or has an invalid `item` configuration. If you use Discord, please join our Discord server for future questions: https://discord.magicspells.dev/

**Comment by StarGlaxeon** [comment]
Well can you help me try to figure it out.

**Comment by JasperLorelai** [comment]
I have... Have you tried it?

**Comment by StarGlaxeon** [comment]
I meant with trying to find the invalid item, I have tried for weeks to find it and i can't what is missing

**Comment by JasperLorelai** [comment]
I'm assuming that `/menu` is an incantation of a Menu spell? If so, could you send just that menu spell on pastebin?

**Comment by StarGlaxeon** [comment]
https://pastebin.com/B8qgmQB2

**Comment by JasperLorelai** [comment]
I can't seem to access it. Did you see it on private?
> Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.

**Comment by StarGlaxeon** [comment]
[Magicspells menu2.txt](https://github.com/TheComputerGeek2/MagicSpells/files/6964376/Magicspells.menu2.txt)
 It wouldnt let me add it as public for safety reasons

**Comment by JasperLorelai** [comment]
This is really odd, but I'm not getting the same issue. What version of MagicSpells and Minecraft are you using? Please send the full version of MagicSpells, as seen by executing `/version MagicSpells` in game. Also, are you using Paper or Spigot?

**Comment by StarGlaxeon** [comment]
4.0 beta 9 and i am using paper.

**Comment by JasperLorelai** [comment]
Ah. Beta 9 does not support 1.17.x. You need to get beta 10. However, all of beta 10 builds are in a special Tester program on our Discord server.

Are you HaleyDanielle#4266, by chance?

**Comment by StarGlaxeon** [comment]
Yes I am HaleyDanielle

**Comment by JasperLorelai** [comment]
I noticed you were locked out. Usually, to access the Discord server, users have to read through the Welcome channel and run a command from there to verify and get access to the rest of the channels. But some keywords like asking for help lock you out to only that channel. So, please read through the channel to verify.

Afterwards, you can ping Dragon (or any Admin) and ask him to give you the Tester role. Once he does, you'll be able to download beta 10.

**Comment by StarGlaxeon** [comment]
Thank you so much!
