### ISSUE TITLE
[12:59:04 WARN]: [MagicSpells] Task #6552665 for MagicSpells v3.6-dev-1906230222 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by TanoBrothers** [TheComputerGeek2/MagicSpells#480]
[12:59:04 WARN]: [MagicSpells] Task #6552665 for MagicSpells v3.6-dev-1906230222 generated an exception
java.lang.NullPointerException: null

How can I solve it?

**Comment by DragonsAscent** [comment]
You're using a build from 2 years ago, we don't support 3.6. please do not open GitHub issues for support. GitHub issues are to report active bugs in the plugin.

If you need support go to https://discord.magicspells.dev/
