### ISSUE TITLE
Probably the error occurs when using Particle in 1.17.1.

### ISSUE THREAD

**Issue by ElseJunsuk** [TheComputerGeek2/MagicSpells#495]
![image](https://user-images.githubusercontent.com/53819958/134810267-b10e6ce3-a19b-4f2e-95ec-1c6f6a29b69b.png)

I used the ProjectileSpell spell, and this is probably an issue with the 1.17.1 update.
Is it not available in 1.17.1?

Spell file:
![image](https://user-images.githubusercontent.com/53819958/134810347-778368da-ef22-4174-a653-a87ab7928109.png)

**Comment by Chronoken** [comment]
You are not using paper. For more help use our discord server.
