### ISSUE TITLE
Custom-name not being applied to armorstand in armorstand effect

### ISSUE THREAD

**Issue by AkitoBurrito** [TheComputerGeek2/MagicSpells#527]
If you cast a spell that has the effect position "projectile" and use the armorstand effect, the custom-name does not apply to the armorstand. Oddly, custom-name works fine with the TotemSpell.

MagicSpells Version: 4.0-Beta-10

Config: https://pastebin.com/S2JNtnJe

**Comment by tonythemacaroni** [comment]
The option is called `custom-name-visible`, not ` custom-name-visibility` - the wiki was documented incorrectly, rather than it being a bug.
