### ISSUE TITLE
Add `buff.LoopSpell`

### ISSUE THREAD

**Issue by DragonsAscent** [TheComputerGeek2/MagicSpells#542]
A spell that allows you to consecutively run a spell every 20 ticks. The `duration` would be in seconds to mitigate damage to TPS and you'd be able to define `spells` to fire every time the spell ticks.

This spell should also be cleansable using the `.targeted.CleanseSpell` as `loop:LoopSpellName`

This would address many issues with multi loops harming newer players.

**Comment by Chronoken** [comment]
Working on a targeted version of this spell atm.
