### ISSUE TITLE
Add `str-on-teach`

### ISSUE THREAD

**Issue by DragonsAscent** [TheComputerGeek2/MagicSpells#547]
Allows you to define a special string to play when teaching specific spells. This is helpful for servers that want to either hide teach for specific spells and or want some spells to be taught as "You've learnt the 'Super Kick' ability!" whereas magic would be "You discovered the 'Fireball' spell". Could also make passives and such say "You're now able to vanish when sneaking", "You've learnt how to double jump, etc.

**Comment by Chronoken** [comment]
Implemented.
