### ISSUE TITLE
I NEED HELP !

### ISSUE THREAD

**Issue by loda0021** [TheComputerGeek2/MagicSpells#60]
Recently, I faced one error.My server is in version 1.10.2 and the plugin Magic spell is also on this version,but the problem is that when the players come to the server: 1)Server hangs,but if you remove the plugin then everything is perfect. 2) I noticed that if I remove my spells which weigh 350 mb it works fine,please help with this problem.

**Comment by TheComputerGeek2** [comment]
I cannot assist in the resolution unless you are able to provide exact conditions and procedure to reproduce the issue. Additionally, the lag on server join is commonly associated with PermissionsEX (a specific permission manager).

**Comment by Niblexis** [comment]
If removing PermissionsEX does not solve your issue:

What version of the MagicSpells plugin are you using on your server? Are you getting any errors in the console of the server, or in the MagicSpells error folder?
