### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by 1lakks** [TheComputerGeek2/MagicSpells#81]
Hello.
I download the recent version of MagicSpells. However, the plugin just doesn't load on to my server. Like i cant use any commands, its not on the plugins list, a folder isnt created. I tried later versions but still it doesnt work. I tried V3.5 and it works but some of the spells I created don't work. ParticleProjectile Spell is bugged. My spell config is 946 KB.

**Comment by salty3773** [comment]
I also have this same problem

**Comment by DragonsAscent** [comment]
We have a discord for a reason. This sounds like formatting issues and if you want support for configuration issues you need to go to the discord. This is meant for source code issues.

@1lakks @salty3773

**Comment by 1lakks** [comment]
It doesnt matter now, it turns out it was because I had PEX and Magicspells.
