### ISSUE TITLE
MagicSpells + Json model connection

### ISSUE THREAD

**Issue by khrstz** [TheComputerGeek2/MagicSpells#854]
Hello.
I'm playing on version 1.12.2
Is it possible to make a chidori spell, but so that when you use it, a 3D json model appears on your hand?
Could you give me an example of a spell, please?

**Comment by Chronoken** [comment]
Github issues aren't for support help, use the discord linked in the project readme.
Besides 1.12.2 isn't supported anymore, so we don't provide help for such an ancient version.

**Comment by khrstz** [comment]
Thanks for the answer!

Forgive me, this is very important to me! I am from Russia and newer versions are not supported in our region, and we also do not have textbooks for studying..
